import streamlit as st
import pandas as pd
from openai import OpenAI
import os
from dotenv import load_dotenv
try:
    df = pd.read_csv("Cartoon_datasets.csv")
except Exception as e:
    st.error(f"Error loading CSV file: {e}")
    st.stop()

st.title("Cartoon Data Query Interface")

load_dotenv()
api_key = os.getenv("API_KEY") or (st.secrets["API_KEY"] if "API_KEY" in st.secrets else None)

if not api_key:
    st.error("API_KEY not found. Please check your Streamlit Secrets or local .env file.")
    st.stop()

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=api_key,
)

question = st.text_input("Enter your query about the cartoon data:")

if question:
    try:
        prompt = f"""You are a Python Pandas Query Generator.
Your job is to generate a valid pandas dataframe query string based on the user's question.
The dataframe is named 'df' and has the following columns: "Name", "Span", "Description", "Rating".

Rules:
1. Return ONLY the executable python statement that filters the dataframe.
2. Do NOT add explanation, markdown code blocks, or comments.
3. Keep it extremely simple.

Example user question: "Find cartoons with a rating higher than 8"
Example Output: df[df['Rating'] > 8]

Example user question: "Search for Batman Beyond"
Example Output: df[df['Name'].str.contains('Batman Beyond', case=False, na=False)]

User Question: {question}
Output:"""

        with st.spinner("Searching the cartoon database..."):
            response = client.chat.completions.create(
                model="meta-llama/llama-3-8b-instruct:free", 
                messages=[{"role": "user", "content": prompt}]
            )
            
            raw_query = response.choices[0].message.content.strip()
            
            raw_query = raw_query.replace("```python", "").replace("```", "").strip()
            
            st.write("**Generated Query:**", f"`{raw_query}`")
            
            if raw_query.startswith("df"):
                result_df = eval(raw_query)
                
                if not result_df.empty:
                    st.success(f"Found {len(result_df)} results!")
                    st.dataframe(result_df)
                else:
                    st.warning("No data found for this query.")
            else:
                st.error("Invalid query generated by AI. Try rephrasing your question.")

    except Exception as e:
        st.error(f"An error occurred: {e}")